### ISSUE TITLE
How to run the demo?

### ISSUE THREAD

**Issue by JennyWJN** [QuentinRoy/Marking-Menu#55]
Hi, may I ask how can I run the demo locally? There's not a start file...

**Comment by QuentinRoy** [comment]
Hi @JennyWJN, thank you for the heads up, I should add some instructions in the readme.

In the meantime, I am depending on [`yarn`](https://yarnpkg.com) so you will need it installed. Once you have this, you may run the following commands in a terminal:
```
yarn install  # Install the dependencies required to build the library
yarn build  # Build the library
yarn serve  # Start a webserver to see the demo
```

Let me know if you run in any issue.

**Comment by JennyWJN** [comment]
Hi, I want to know what's the relationship between the folder "demo" and others like "src". I notice that  this project can run after I delete some folders like src and build_config.

**Comment by QuentinRoy** [comment]
`src` contains the source code of the library. `build_config` contains stuff to compile the source code (and create `marking-menu.js`).
`demo` is using the compiled version (`marking-menu.js`). It does not depend directly on `src` and `build_config` (nothing should), but it does depend on what they produce. As a result, once you get the compiled code, removing them won’t prevent the demo to work.

**Comment by JennyWJN** [comment]
I see, thank you!

**Comment by JennyWJN** [comment]
Hi, I'm trying to implement a marking menu with nodeJS, but when I import 'menu.pug' to my js file, the browser's console output an error that 'Failed to load module script: The server responded with a non-JavaScript MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.(menu.pug:1)' Do you know how to solve it? I think there may be some configuration I didn't know. Thank you very much.

**Comment by JennyWJN** [comment]
Hi, I'm trying to implement a marking menu with nodeJS, but when I import 'menu.pug' to my js file, the browser's console output an error that _'Failed to load module script: The server responded with a non-JavaScript MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.(menu.pug:1)'_ 
When I use app.set('view engine', 'pug'), there's an error '_GET http://localhost:3000/views/menu.pug net::ERR_ABORTED 404 (Not Found)_'.  Do you know how to solve it? Thank you very much.

**Comment by QuentinRoy** [comment]
I want to get rid of this pug template, it is not much useful and complexifies the building process...
You will not be able to load this file directly. It needs to be compiled. How are you importing the library in your project?

**Comment by JennyWJN** [comment]
I can compile and run your code. But now I'm writting my own project on marking menu and want to use a template as yours in my project. As I don't use rollup config, I don't know how to compile it using other methods.

**Comment by QuentinRoy** [comment]
Compile it using my rollup config, then import the compiled version in your project. But you said it is a nodeJS project? Is it supposed to run in a browser eventually?

**Comment by QuentinRoy** [comment]
Overall, these instructions should cover most use cases: https://github.com/QuentinRoy/Marking-Menu#install. You should not have to deal with the sources. I am not too sure what you are trying to do, but if you are not following any of these options, there is a very good chance you are making your life more complicated than what it could be.
